2 web
Avrooid/Machines pull request #2
Opened 2023-03-21 14:58 UTC by Avrooid

2023-03-24 15:39 UTC, Sw24sX requested changes
Опиши, пожалуйста, идею своего проекта в README файле)

2023-03-24 15:39 UTC, Sw24sX commented on src/main/java/ru/Burakov/Machines/SpringConfig.java
> +@Configuration
Пустой конфиг файл - это лишнее

2023-03-24 15:39 UTC, Sw24sX commented on src/main/java/ru/Burakov/Machines/controllers/CarController.java
> +        HashMap<String, String> map = new HashMap<>();
Старайся использовать интерфейсы при объявлении переменных, полей, аргументов и тд, вместо реализаций (Вместо HashMap - Map, вместо ArrayList или LinkedList - List и тд).
т.е твоя строка выглядела бы так:
`Map<String, String> map = new HashMap<>();`
Поправь это в остальных местах проекта)

2023-03-24 15:39 UTC, Sw24sX commented on src/main/java/ru/Burakov/Machines/controllers/CarController.java
> +            map.put(key, value.stream().collect(Collectors.joining("|")));
`value.stream().collect(Collectors.joining("|")))` эквивалентно `String.join("|", value)`, но выглядит короче)

2023-03-24 15:39 UTC, Sw24sX commented on src/main/java/ru/Burakov/Machines/dao/ElectricCarDAO.java
> +        electricEngine.setId(++id);
Подход интересный, но несколько неверный.
Проблема вот в чем: у нас в рамках одного запроса код выполняется в одном потоке, но все запросы относительно друг друга выполняются параллельно.
Да, твой сервис singleton и в теории значение id будет увеличиваться для всех потоков, но проблема в том, что это не атомарная операция.
При значительном количестве потоков (запросов) есть вероятность дублирования id, а ты вроде как стремился сделать так, чтобы они были уникальными.
Пара статей тебе для изучения:
https://alexbtw.livejournal.com/3355.html
http://java.msk.ru/не-атомарность-i-volatile-и-synchronized/
https://java-online.ru/concurrent-atomic.xhtml

2023-03-24 15:39 UTC, Sw24sX commented on src/main/java/ru/Burakov/Machines/dao/ElectricCarDAO.java
> +    private ArrayList<ElectricCar> electricCars = new ArrayList<>();
Пока мы не знаем про бд, для такого хранения данных наверно более подходящим была бы Map, хотя тут тебе виднее

2023-03-24 15:39 UTC, Sw24sX commented on src/main/java/ru/Burakov/Machines/exceptions/ResponseError.java
> +    private HttpStatus httpStatus;
А тебе не кажется излишним отправлять статус в теле ответа?
У тебя в теории могут возникнуть ситуации, когда статус сообщения один, а статус в теле - другой.
Ты можешь написать здесь коммент, если считаешь по-другому)

2023-03-24 15:40 UTC, Sw24sX commented
Поставил 4, если исправишь замечания или опишешь, почему твое код корректен - добавлю до 5)

2023-03-25 10:03 UTC, Avrooid commented on src/main/java/ru/Burakov/Machines/exceptions/ResponseError.java
> +    private HttpStatus httpStatus;
Но я же возвращаю ResponseError в Advice, то есть я в зависимости от ошибки могу вернуть разный httpstatus, я подумал будет удобно для фронта и тестеров(м.б. в будущем), если помимо времени и сообщения будет выводиться еще httpstatus в json формате. Хотя может я ошибаюсь, я не ещё не настолько глубоко вникся в тему обработки ошибок в спринге.

2023-03-25 10:19 UTC, Avrooid commented on src/main/java/ru/Burakov/Machines/dao/ElectricCarDAO.java
> +    private ArrayList<ElectricCar> electricCars = new ArrayList<>();
Я потом еще сущности менять буду точно(скорее всего уберу Id у двигателей и дам их машинам, а может ещё что-то добавиться по необходимости, поэтому на мой взгляд удобней пока что список использовать)

2023-03-25 14:27 UTC, Sw24sX commented on src/main/java/ru/Burakov/Machines/exceptions/ResponseError.java
> +    private HttpStatus httpStatus;
Ну смотри, у нас статус ответа в HTTP есть всегда, поэтому дублирование его в теле ответа - это лишняя информация. Фронт легко обрабатывает статус ответа, так как это стандартный формат, а также могут его спокойно увидеть в DevTools (если браузер) или в Postman и аналогах.

Ну и помимо дублирования информации у нас появляется вероятность различия между статусом в теле и реальным статусом. Например, при обработке нового исключения ты забудешь установить такой-же статус или намеренно ты или кто-то, кто будет пользоваться твоим кодом захочешь передавать другой статус в теле.

При обработке ошибки ты возвращаешь точно такое же ответ, если бы ты возвращал его обычным штатным способом (имею ввиду одинаковый формат). В штатном случае у тебя с сообщением передается статус 200, при обработке ошибки ты можешь конфигурировать это значение, но так или иначе это значение вынесено отдельно в HTTP

2023-03-25 15:20 UTC, Avrooid commented on src/main/java/ru/Burakov/Machines/exceptions/ResponseError.java
> +    private HttpStatus httpStatus;
Хорошо, сейчас исправлю

2023-03-25 17:16 UTC, Sw24sX commented
Все хорошо, оценку изменил)

2023-03-29 15:53 UTC, merged